ERROR:root:can't use "pyimage132" as iconphoto: not a photo image
Traceback (most recent call last):
  File "d:/Python/New Projects/Sounder5/Sounder5.py", line 1280, in import_settings
    Sounder().mainloop()
  File "d:/Python/New Projects/Sounder5/Sounder5.py", line 56, in __init__
    self.load_icons()
  File "d:/Python/New Projects/Sounder5/Sounder5.py", line 248, in load_icons
    self.iconphoto(False, self.icons['logo'])
  File "C:\Users\Mateusz\AppData\Local\Programs\Python\Python38\lib\tkinter\__init__.py", line 2118, in wm_iconphoto
    self.tk.call('wm', 'iconphoto', self._w, *args)
_tkinter.TclError: can't use "pyimage132" as iconphoto: not a photo image
ERROR:root:'update'
Traceback (most recent call last):
  File "d:/Python/New Projects/Sounder5/Sounder5.py", line 863, in check_update
    ttk.Radiobutton(self.menu_panel, image=self.icons['update'], text='Update', compound='left', value='Update', variable=self.menu_playlist, command=self.show_panel).pack(side='top', fill='x', padx=10)
KeyError: 'update'
ERROR:root:can only concatenate str (not "int") to str
Traceback (most recent call last):
  File "d:/Python/New Projects/Sounder5/Sounder5.py", line 871, in check_update
    self.prepare_update_panel()
  File "d:/Python/New Projects/Sounder5/Sounder5.py", line 882, in prepare_update_panel
    self.show_panel()
  File "d:/Python/New Projects/Sounder5/Sounder5.py", line 602, in show_panel
    self.show_panels(target_panel)
  File "d:/Python/New Projects/Sounder5/Sounder5.py", line 641, in show_panels
    for update in self.update_panels:
  File "C:\Users\Mateusz\AppData\Local\Programs\Python\Python38\lib\tkinter\__init__.py", line 1643, in cget
    return self.tk.call(self._w, 'cget', '-' + key)
TypeError: can only concatenate str (not "int") to str
ERROR:root:tuple indices must be integers or slices, not Frame
Traceback (most recent call last):
  File "d:/Python/New Projects/Sounder5/Sounder5.py", line 871, in check_update
    self.prepare_update_panel()
  File "d:/Python/New Projects/Sounder5/Sounder5.py", line 882, in prepare_update_panel
    self.show_panel()
  File "d:/Python/New Projects/Sounder5/Sounder5.py", line 602, in show_panel
    self.show_panels(target_panel)
  File "d:/Python/New Projects/Sounder5/Sounder5.py", line 642, in show_panels
    if not self.update_panels[update].winfo_ismapped():
TypeError: tuple indices must be integers or slices, not Frame
ERROR:root:unsupported operand type(s) for /: 'str' and 'int'
Traceback (most recent call last):
  File "d:/Python/New Projects/Sounder5/Sounder5.py", line 876, in check_update
    print(package_size / 1024)
TypeError: unsupported operand type(s) for /: 'str' and 'int'
ERROR:root:list assignment index out of range
Traceback (most recent call last):
  File "d:/Python/New Projects/Sounder5/Sounder5.py", line 877, in check_update
    self.prepare_update_panel(server_version, f'{round(float(float(int(package_size) / 1024) / 1024), 1)}')
  File "d:/Python/New Projects/Sounder5/Sounder5.py", line 925, in prepare_update_panel
    self.update_panel(package_size, version)
  File "d:/Python/New Projects/Sounder5/Sounder5.py", line 896, in update_panel
    self.update_panels[0] = None
IndexError: list assignment index out of range
ERROR:root:list assignment index out of range
Traceback (most recent call last):
  File "d:/Python/New Projects/Sounder5/Sounder5.py", line 877, in check_update
    self.prepare_update_panel(server_version, f'{round(float(float(int(package_size) / 1024) / 1024), 1)}')
  File "d:/Python/New Projects/Sounder5/Sounder5.py", line 925, in prepare_update_panel
    self.update_panel(package_size, version)
  File "d:/Python/New Projects/Sounder5/Sounder5.py", line 896, in update_panel
    self.update_panels[0] = None
IndexError: list assignment index out of range
ERROR:root:update_panel() missing 1 required positional argument: 'package_details'
Traceback (most recent call last):
  File "d:/Python/New Projects/Sounder5/Sounder5.py", line 877, in check_update
    self.prepare_update_panel(server_version, f'{round(float(float(int(package_size) / 1024) / 1024), 1)}')
  File "d:/Python/New Projects/Sounder5/Sounder5.py", line 932, in prepare_update_panel
    self.update_panel(package_size, version)
TypeError: update_panel() missing 1 required positional argument: 'package_details'
ERROR:root:Object of type TextIOWrapper is not JSON serializable
Traceback (most recent call last):
  File "d:/Python/New Projects/Sounder5/Sounder5.py", line 112, in init_settings
    dump(data, default_updates)
  File "C:\Users\Mateusz\AppData\Local\Programs\Python\Python38\lib\json\__init__.py", line 179, in dump
    for chunk in iterable:
  File "C:\Users\Mateusz\AppData\Local\Programs\Python\Python38\lib\json\encoder.py", line 438, in _iterencode
    o = _default(o)
  File "C:\Users\Mateusz\AppData\Local\Programs\Python\Python38\lib\json\encoder.py", line 179, in default
    raise TypeError(f'Object of type {o.__class__.__name__} '
TypeError: Object of type TextIOWrapper is not JSON serializable
ERROR:root:'NoneType' object is not iterable
Traceback (most recent call last):
  File "d:/Python/New Projects/Sounder5/Sounder5.py", line 874, in check_update
    self.prepare_update_panel(server_version)
  File "d:/Python/New Projects/Sounder5/Sounder5.py", line 946, in prepare_update_panel
    self.update_panel(package_size, package_version, package_details, updates_history)
  File "d:/Python/New Projects/Sounder5/Sounder5.py", line 905, in update_panel
    for update in updates_history['Updates'].reverse():
TypeError: 'NoneType' object is not iterable
ERROR:root:'NoneType' object is not iterable
Traceback (most recent call last):
  File "d:/Python/New Projects/Sounder5/Sounder5.py", line 874, in check_update
    self.prepare_update_panel(server_version)
  File "d:/Python/New Projects/Sounder5/Sounder5.py", line 946, in prepare_update_panel
    self.update_panel(package_size, package_version, package_details, updates_history)
  File "d:/Python/New Projects/Sounder5/Sounder5.py", line 905, in update_panel
    for update in updates_history['Updates'].reverse():
TypeError: 'NoneType' object is not iterable
ERROR:root:local variable 'updates_history' referenced before assignment
Traceback (most recent call last):
  File "d:/Python/New Projects/Sounder5/Sounder5.py", line 873, in check_update
    self.prepare_update_panel(server_version)
  File "d:/Python/New Projects/Sounder5/Sounder5.py", line 942, in prepare_update_panel
    self.update_panel(package_size, package_version, package_details, updates_history)
UnboundLocalError: local variable 'updates_history' referenced before assignment
